### ISSUE TITLE
World / Singleton macht große Probleme :(

### ISSUE THREAD

**Issue by BatsiMcLovin** [traubenzucker3001/AnSimSS15-source#11]
Wir kommen mit der Handhabung der Singleton Klasse nciht so richtig zurecht....
Wir können keine Methoden aus der World-Klasse benutzen.... 
Wenn du mit der Handhabung vertraut bist, lass es uns wissen ;)

**Comment by traubenzucker3001** [comment]
um Funktionen oder Attribute anzusprechen verwendet man normal  ja:
World::getInstance()->...

aber wenn das nicht geht.... einfachte Lösung: 
Singelton weg lassen, wir bauen ja unsere Demo selbst und passen auf, dass nur eine World erstellt wird.

**Comment by traubenzucker3001** [comment]
hab gerade nochmal geschaut, bei meiner BA hatte ich auch irgwelche Probleme damit und hab es dann nicht als Singleton modelliert.

**Comment by Koerv** [comment]
Haben jetzt im Endeffekt die World-Klasse gar nicht benutzt und Sachen wie die gravity direkt über die main.cpp gesteuert.. funzt aber auch und reicht ja für das, was wir tun wollten

**Comment by traubenzucker3001** [comment]
ja klar, reicht völlig es über die main zu machen, bauen ja keine Engine die andere ("Unwissende") benutzten sollen^^

**Comment by traubenzucker3001** [comment]
World-Klasse ignorieren ist somit die Lösung^^ ...damit cloesd
