### ISSUE TITLE
Inertia Tensor für Rakete

### ISSUE THREAD

**Issue by traubenzucker3001** [traubenzucker3001/AnSimSS15-source#2]
einen geeigneten Inertia Tensor für die Form der Rakete finden.

mal im Web schauen oder zur Not selber bestimmen, geht wohl indem man die Form mit Partikeln füllt und dann irgendwie berechnet 
(Game Physics Engine Development - S.198 ff.) 
(Game Physics - S.55 ff.)

**Comment by BatsiMcLovin** [comment]
schöne simple erklärung von inertia tensor, falls das aus der vorlesung fürs verständnis nicht reicht...

https://www.techhouse.org/~dmorris/projects/tutorials/inertia.tensor.summary.pdf

**Comment by BatsiMcLovin** [comment]
Das ist alles erledigt.... 
Für verschiedene Geometrien kann man hier ganz gut nachschauen:
https://en.wikipedia.org/wiki/List_of_moments_of_inertia

gerade die untere Tabelle ist hilfreich.
