### ISSUE TITLE
Force that is not acting on the Center of Mass

### ISSUE THREAD

**Issue by traubenzucker3001** [traubenzucker3001/AnSimSS15-source#3]
nachlesen wie Kraft die nicht auf das Messezentrum wirkt behandelt werden muss.
für die Triebwerke der Rakete.

**Comment by traubenzucker3001** [comment]
Ist nachgelesen. 
hat besondere Auswirkung auf Drehmoment 
--> (Game Physics Engine Development - S. 197 - Drehmoment) 
--> (Game Physics - S.36 - Drehmonet)

*todo: in Code umsetzten !!!

**Comment by BatsiMcLovin** [comment]
Haben wir soweit eigentlich umgesetzt..... Vllt stimmen noch ein paar Details nicht, aber im Großen und Ganzen haben wir Inertia Tensor, etc bereits implementiert... Ausserdem nochmal ein dickes Dankeschön für deine Vorarbeit in der RigidBody-Klasse.

ABER: Wir haben noch eine gewaltige Verständnislücke:
                  Wenn eine Kraft, nciht auf das Massezentrum wirkt, wie wird die Kraft auf Rotation bzw. 
                  Translation verteilt.

Wenn du jemand dazu was findet, unbedingt hier posten!

**Comment by BatsiMcLovin** [comment]
haben es.... und auch schon implementiert...
