### ISSUE TITLE
Darstellung Rakete

### ISSUE THREAD

**Issue by traubenzucker3001** [traubenzucker3001/AnSimSS15-source#4]
soll ein Model eingeladen werden (aus Web oder so) oder bauen wir uns die Form der Rakete selber?!

ist die draw-Methode direkt in der Rocket.h/.cpp untergebracht oder trennen wir Darstellung und Physik über z.B. ein VirtualObject (dass dann aus "physic component" = RigidBody und "graphic component" = ... besteht)?!

**Comment by BatsiMcLovin** [comment]
Zum trennen von Physic und Graphics hab ich null plan.... aber da wir ja mit den inertia tensors arbeiten, nehmen wir einfach ne simple geometrische Form wie ne elipse oder nen cone.... da gibt es nämlich die inertia tensors auf wiki

**Comment by BatsiMcLovin** [comment]
also ich kann auch innerhalb von wenigen minuten eine simple rakete in blender erstellen.... auch kein ding...

**Comment by BatsiMcLovin** [comment]
https://dl.dropboxusercontent.com/u/105118065/sphere.obj

ein simpler elipsoid als .obj
sollte in die resources, also bitte runterladen, sonst sieht man kein model in der demo...

**Comment by traubenzucker3001** [comment]
ich sehe am Laptop zwar eh nichts (kein opengl 3.3 unterstützt), aber .obj ist schon mal im resources-Ordner.

**Comment by traubenzucker3001** [comment]
also man könnte halt ein VirtualObjekt (VO) erstellen das aus einer physikalischen und einer grafischen Komponente besteht. Die physikalische wäre dabei ein RigidBody als Vereinfachung der eigentlichen Form, die graphische dann ein Knoten im Szenegraphen mit dem wirklich dargestellten Modell. Während der Simulation wird dann nur das RigidBody beachtet. Mit einer entsprechenden update-Methode in der VO-Klasse kann man dann aus der Position und Rotation des RigidBodies die Modelmatrix für das Modell berechnen.
Ist eigentlich keine große Sache aber bin mir nicht sicher ob das bei so einem "kleinen" Projekt nötig ist.

ein Blick in meinen BA-Code hilft vielleicht zum Verständnis, das ist der "RBPE-source" auf meiner Account-Titel-Seite: 
RBPE-source/src/libraries/PhysicEngine/VirtualObject.h und .cpp

**Comment by BatsiMcLovin** [comment]
Die Trennung von der du Sprichst besteht schon in unserem Projekt.

-Die Graphics-Component ist zur Zeit ein Scene-Node mit Modelmatrix und Model von der Rakete.
-Die Physics-Component ist eben unser Rigid Body....

Und ich denke du hast Recht, wenn wir dazu kein extra Virtual Object brauchen.
Denke dieses Issue können wir damit schließen ;)
