### ISSUE TITLE
Physik Komponenten

### ISSUE THREAD

**Issue by traubenzucker3001** [traubenzucker3001/AnSimSS15-source#5]
alles Nötige für die Simulation:
- RigidBody Physik
- etc.

**Comment by BatsiMcLovin** [comment]
Außer eventuellen Bug-Fixes haben wir soweit alles für die Rakete.... Sollten wir jedoch noch Partikel für die "Triebwerke" erstellen wollen, müssen wir da noch geringfügig was ändern.
