### ISSUE TITLE
Grafik Komponenten

### ISSUE THREAD

**Issue by traubenzucker3001** [traubenzucker3001/AnSimSS15-source#6]
alles Nötige für die Darstellung:
- Model der Rakete
- etc.

**Comment by BatsiMcLovin** [comment]
wenn alle stricke reißen, nehmen wir die rakete aus exercise 3.... die hätten wir schon...

**Comment by BatsiMcLovin** [comment]
Also Model, wird von mir in Blender erstellt, muss ja nicht zu aufwendig sein.... einfache geometrische Körper sollten reichen.
