### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by traubenzucker3001** [traubenzucker3001/AnSimSS15-source#7]
alles Nötige für eine laufende Demo:
- CVK-Umgebung (Fenster, Kamera, Shader, etc.)
- richtiger Ablauf der Simulation und entsprechender Darstellung
- etc.

**Comment by BatsiMcLovin** [comment]
Die Umgebung haben wir bereits.
Nehmen die von exercise 3 da ist alles schon bereitgestellt. Da müssten wir nurnoch an unsere bedürfnisse anpassen.

**Comment by traubenzucker3001** [comment]
das ist ja schon mal schön, Arbeit gespart... weiter so^^

**Comment by BatsiMcLovin** [comment]
sind dem ganzen einen riesen schritt näher gekommen....
Wir haben nun die Umgebung, ein Space-ship und eine kraft die das ganze anschiebt, rotiert und rendert.....

Fummeln grade noch an der Camera, dass die unserem Spaceship folgt :)

**Comment by BatsiMcLovin** [comment]
DONE!
