### ISSUE TITLE
nötige Kräfte

### ISSUE THREAD

**Issue by traubenzucker3001** [traubenzucker3001/AnSimSS15-source#8]
welche Kräfte sollen wir mit einbauen?!
2 Kräfte, die per Tastendruck erzeugt werden, für die Triebwerke ist ja schon mal klar.
aber soll auch Gravitation mit in die Simulation? oder sogar noch weitere Kräfte?!

**Comment by BatsiMcLovin** [comment]
Lass uns erstmal ohne Schwerkraft arbeiten, wenn das im Outer Space funzt, dann können wir damit auch auf die Erde...

**Comment by traubenzucker3001** [comment]
alles klar, da haste recht.

**Comment by BatsiMcLovin** [comment]
nun klappt alles im Weltraum..... nächster schritt ist es jetzt schwerkraft einzubauen....
