### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by BatsiMcLovin** [traubenzucker3001/AnSimSS15-source#9]
Da nun alles soweit klappt.... Lasst uns versuchen einen "authentischen" Raketenstart hinzubekommen...

**Comment by traubenzucker3001** [comment]
Gravitation hinzufügen ist eigentlich nur eine Zeile:

```
force.y = force.y + mass * -gravity; //force of gravity
```

bevor der neue Impuls (Momenta) des RigidBody berechnet wird, wird einfach auf die y-Komponente seiner momentanen Kraft noch die Masse \* 9,81..... auf addiert.

**Comment by BatsiMcLovin** [comment]
da hast du absolut Recht :)
